### ISSUE TITLE
rubocopConfigFile not working

### ISSUE THREAD

**Issue by Simas1** [pendrica/vscode-chef#29]
Hi,

I have issue with rubocop rules. In my cookbook I have .rubocop.yml file with rules, if I run rubocop command in VSCode terminal (workspace root) without any parameters it works and pickup my .rubocop.yml file.
But this extension marks problems in files and not loading .rubocop.yml, also if I try to specify "rubocop.configFile": ".rubocop.yml" -- this is not working also (but no errors on console log). And if I put vscode variable: "rubocop.configFile": "${workspaceFolder}/.rubocop.yml" -- then extension fails with errors:
`[Extension Host] Using custom Rubocop config from: ${workspaceFolder}/.rubocop.yml
[Extension Host] SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at validateWorkspace (C:\Users\SIMAS\.vscode\extensions\pendrica.chef-0.7.0\out\extension.js:102:34)
at vscode.workspace.onDidSaveTextDocument.document (C:\Users\SIMAS\.vscode\extensions\pendrica.chef-0.7.0\out\extension.js:140:9)
at e.fire (c:\Users\SIMAS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
at e.$acceptModelSaved (c:\Users\SIMAS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:485:586)
at t._doInvokeHandler (c:\Users\SIMAS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:888)
at t._invokeHandler (c:\Users\SIMAS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:554)
at t._receiveRequest (c:\Users\SIMAS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:126)
at t._receiveOneMessage (c:\Users\SIMAS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:59)
at c:\Users\SIMAS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
at c:\Users\SIMAS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
at e.fire (c:\Users\SIMAS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
at a (c:\Users\SIMAS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
at Socket._socketDataListener (c:\Users\SIMAS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
at Socket.Readable.push (_stream_readable.js:208:10)
at Pipe.onread (net.js:594:20)
`

Can we add vscode variables support in rubocop.configFile? So that rubocopConfigFile can be full path or just filename

P.S> Do we need this third parameter? (vscode.workspace.rootPath), if you already launch process in working directory (cwd):
`rubocop = spawn(rubocopPath, ["--config", rubocopConfigFile, "-f", "j", vscode.workspace.rootPath]`

I use ChefDK: 2.5.3 (unfortunately I can't use new version, because our pipeline needs compatibility)
VSCode: 1.28.1
Chef Extension: 0.7.0
OS: Windows 7 64bit

Thanks,
Simas

**Comment by Simas1** [comment]
Just looking to source code, and I found how to solve my problem, I need to pass rubocop full path:
```
"rubocop.path": "C:/opscode/chefdk/embedded/bin/rubocop.bat",
"rubocop.configFile": ".rubocop.yml",
```
This is disabling cookstyle.bat (which is now made default), and seems cookstyle ignore .rubocop.yml or do not understand the format (I'm not sure reason - you saw errors).
So I guess it would be nice that rubocop and cookstyle settings will be separated (or even given option to select which one to use), because now it's confusing.

**Comment by Simas1** [comment]
Seems not all issues solved with rubocop :(

Now most of issues solved when rubocop start reading .rubocop.yml file, but problem still exist with such rules:
```
Lint/UnusedMethodArgument:
  Exclude:
    - 'files/dispatcher.rb'
```
If I exclude whole file, this extension don't understand that and marks this as problem and I get a lot of issues because of that file, but if I run rubocop on terminal it will show me 0 issues.

How to solve that?

**Comment by Simas1** [comment]
And another annoying thing is that if i change rubocop.configFile string on user settings, it will ignore these settings until I restart vscode.

**Comment by tyler-ball** [comment]
Hey @Simas1, sorry for such a late reply. Are you able to try the latest version of the extension with the latest version of Chef Workstation? We made updates that should support that setup.
